### ISSUE TITLE
Beaglebone not powering up  

### ISSUE THREAD

**Issue by gov466** [gov466/Capstone-project#1]
I had connected beaglebone black via 5v barrel jack. But it is not powering up. Just once the power led lights and then goes off.
I have checked the voltage at barrel jack which i found as 5v itself.

- [ ] should be solved soon

**Comment by zrajani** [comment]
@gov466 Try Checking for the current you are getting from the supply as the BBB demands a supply of at least 2 A so may be your getting the current less than the desired value. Check this link up for more information: [Ways to power up BBB](https://thepihut.com/blogs/raspberry-pi-tutorials/how-do-i-power-my-beaglebone-black#:~:text=Apart%20from%20the%20USB%20requirement,to%20power%20the%20entire%20board.)

**Comment by gov466** [comment]
The problem was with battery is used. When i changed the battery it was working fine. There was no issue with barrel  jack.

![20201023_101958](https://user-images.githubusercontent.com/54857279/97016070-4a035f00-151a-11eb-84f7-a2c342d02ae1.jpg)
