### ISSUE TITLE
connecting the Arduino to the BBB using a Bluetooth module

### ISSUE THREAD

**Issue by mikeshams** [gov466/Capstone-project#10]
Varundeep - 1) what issues did you face when connecting the Arduino to the BBB wirelessly? 2) how did you fix them?

**Comment by varundeepsethi** [comment]
Issues while connecting Arduino Uno to the BBB wirelessly -

1. Both the devices communicated through the UART port, but the UART ports of Beaglebone Black were not enabled by default. Hence, the communication was not working. So, we had to manually enable the UART ports to get the Beaglebone Black working.

2. Our Arduino Uno was facing an issue where any number after the number '4' was not being displayed. Supposedly, the speed was 345, but the output only said 34. This is the issue that we had. To rectify it, we had to modify the code. The solution was to replace the number '4' with the alphabet 'z.' Now, the speed, which was initially 345, had become 3z5. At the receiver end, we edited the code when we received the alphabet 'z'; it was replaced with the number '4'. So, the final output came out to be 345 (the original speed).

3. While connecting the HM-10 Bluetooth modules, we did not know how to connect the two devices. After enabling them, the LEDs kept on blinking, and we could not establish a connection. After researching it, we found out that both the modules were slave devices by default. So, we had to change the configuration of one of the modules by using multiple AT commands. That is how we were able to establish a connection between them.
