### ISSUE TITLE
component testing

### ISSUE THREAD

**Issue by mikeshams** [gov466/Capstone-project#3]
Govind - What issues did you face when testing the components? How did you fix them?

**Comment by gov466** [comment]
1) Firstly when i tried to powerup beaglebone using barrel jack(5V) beagleone was not booting up. I had already opened an issue for that [https://github.com/gov466/Capstone-project/issues/1](url) .  There was a problem with the battery i used. When i switched the battery to USB cable or wall adapter  it was working fine. Below picture shows the booting of BBB via barrel jack.

![20201023_101958](https://user-images.githubusercontent.com/54857279/97015662-d6615200-1519-11eb-9179-82180457db4e.jpg)
.

2) There was many libraries available in internet for i2c function for lcd. Choosing correct one was an issue.
