### ISSUE TITLE
IR Sensor interfacing

### ISSUE THREAD

**Issue by mikeshams** [gov466/Capstone-project#5]
Sunny - 1) What issues did you face when interfacing the IR Sensors? 2) How did you resolve them? 3) What's the difference between milisec() and RTC() and what is the requirement for having RTC() in your code?

**Comment by MrSunnyDevgan** [comment]
1. The issue faced while interfacing IR sensor was that there are several types of IR Sensors available in market and finding the exact one was bit tricky.

2. We selected the proximity based IR sensor as we have to detect Car. The code reference of the same was easily available.

3. millis() give us the time passed until the device started in milliseconds and RTC() for getting the real time clock. Although we don't need RTC(), we just needed time difference for calculating speed.

4. For RTC() We need extra RTC module DS3231
