### ISSUE TITLE
LCD Interfacing

### ISSUE THREAD

**Issue by mikeshams** [gov466/Capstone-project#6]
Govind - 1) What issues did you face when interfacing the LCD? 2) How did you resolve them? 3) Change the font size

**Comment by gov466** [comment]
1,2-)   -  The main problem was there was no library flies available for doing some operations such as LCD initialization, clear                display etc..  which was found in Arduino when i interfaced LCD using I2C protocol. So these functions where written inside the   main file  itself that made the code longer. 
       - Normally the interfacing of LCD is done using more wires that makes the circuit complex, since we use I2C protocol it was    much easier for wiring and circuit looks simpler and nice. 
       - Pin out of beaglebone shows  P9(pins 5,6,7,8)as 5v pins. So, when i tried to connect power to LCD from beaglebone i was confused to which 5v i should connect. Then after some research i came to know that P9(pin 5 and 6) are used as supply when we power beaglebone through wall adapter(or via barrel jack) and when we use USB cable we should use P9(pins 7 and 8) which is system generated 5v as supply.

3-) Character LCD can display 5x8 and 5x10 font size. In 5xA, 5 is no of columns and A is no of rows. Character LCD's which are controlled by HD44780 can display 5x8 and 5x10 font size character. Before starting to display a word in LCD there are some initialization to be done.(whether there should be cursor visible on LCD or not, font size etc..). All these initialization are done using instruction set in LCD.  Below shown is instruction set of LCD,
![Screenshot from 2020-11-12 16-17-49](https://user-images.githubusercontent.com/54857279/98997622-c5957200-2502-11eb-82bd-fb34812fdc9c.png)

Above shown instruction set shows what values we should use to initialize LCD in 5x10 font size. By keeping the values of instruction set as shown above we can configure LCD in 5x10 font size.

 After doing some research i came to know that all 1602 LCD will not support both font size. There are 1602 LCD that can display font in 5x8 and 5x10 dots. Some may have only function to display 5x8 dots. In this case(LCD with only 5x8 dots) we wont be able to display 5x10 dots.  If we  look deeper into the LCD screen we can see a matrix for each character or we can say as dots and in my case its 5 columns and 8 rows so it wont be possible to display character of 5x10 font size.

[Click here  to LCD having both functionality]( https://www.amazon.com/HiLetgo-LCD1602-Output-expansion-Arduino/dp/B00OGYXN8C)
[Click here to LCD having only single functionality](https://www.digikey.ca/en/products/detail/newhaven-display-intl/NHD-0216K1Z-FL-YBW/1701171?utm_adgroup=Display%20Modules%20-%20LCD%2C%20OLED%20Character%20and%20Numeric&utm_source=google&utm_medium=cpc&utm_campaign=Shopping_Product_Optoelectronics&utm_term=&productid=1701171&gclid=CjwKCAiA17P9BRB2EiwAMvwNyCaMylIWL2F4B7TzOEuZcb8RuJ6YmgXy6zhOG-lh0V1C11m80kmaHRoC6joQAvD_BwE)
